CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL UNIQUE,
    synopsis VARCHAR(1000) NOT NULL,
    genre VARCHAR(60) NOT NULL,
    runtime_minutes INT NOT NULL,
    rating VARCHAR(16) NOT NULL,
    poster_url VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE showings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    theatre VARCHAR(120) NOT NULL,
    screen_name VARCHAR(40) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ticket_price DECIMAL(8, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_showings_movie FOREIGN KEY (movie_id) REFERENCES movies (id)
);

CREATE INDEX idx_showings_starts_at ON showings (starts_at);
CREATE INDEX idx_showings_movie_id ON showings (movie_id);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(16) NOT NULL UNIQUE,
    customer_name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    showing_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    total DECIMAL(9, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bookings_showing FOREIGN KEY (showing_id) REFERENCES showings (id)
);

CREATE TABLE booking_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    showing_id BIGINT NOT NULL,
    seat_label VARCHAR(4) NOT NULL,
    price DECIMAL(8, 2) NOT NULL,
    CONSTRAINT fk_booking_seats_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_seats_showing FOREIGN KEY (showing_id) REFERENCES showings (id),
    CONSTRAINT uk_showing_seat UNIQUE (showing_id, seat_label)
);

CREATE INDEX idx_booking_seats_booking_id ON booking_seats (booking_id);
